version: "3.5"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8080
    networks:
      - backend
    ports:
      - "8080:8080"
  rdbms:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crm_dev
    volumes:
      - ${HOME}/docker/postgres/data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "6666:5432"
  redis:
    image: redis:7.0.2
    restart: always
    networks:
      - backend


networks:
  backend:
