version: "3.5"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "8080:8080"
  rdbms:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: pokemonapi
      POSTGRES_PASSWORD: c0mpl3xp4ssw0rd
      POSTGRES_DB: pokemon_api
    volumes:
      - ${HOME}/docker/postgres/data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "6666:5432"
  redis:
    image: redis:7.0.2
    restart: always
    networks:
      - backend


networks:
  backend:
