spring:
  flyway:
    enabled: true
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
      show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
  redis:
    database: 0
    connect-timeout: 5000

application:
  security:
    authentication:
      excluded:
        - "/v1/authentication/login"
        - "/v1/user"
        - "/sets"
        - "/cards"
        - "/v2/cards"
        - "/v2/sets"
        - "/v1/invoice"
        - "/v1/invoice/**"
        - "/v1/invoice/customer"