DROP TABLE role;

ALTER TABLE users DROP COLUMN role_id;

ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'USER';

ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'));

